# Generated by Django 5.1.15 on 2026-09-17 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discoveredaccount',
            options={'ordering': ('platform_name',)},
        ),
        migrations.AlterModelOptions(
            name='questionnaireresponse',
            options={'ordering': ('question_id',)},
        ),
        migrations.AlterModelOptions(
            name='rawscrape',
            options={'ordering': ('-scraped_at',)},
        ),
        migrations.AlterModelOptions(
            name='target',
            options={'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='ProfileResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework_name', models.CharField(max_length=100)),
                ('score_data', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_results', to='core.target')),
            ],
            options={
                'ordering': ('-generated_at',),
                'unique_together': {('target', 'framework_name')},
            },
        ),
    ]
