# Generated by Django 5.1.15 on 2026-09-17 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_discoveredaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rawscrape',
            unique_together={('target', 'platform_name')},
        ),
    ]
