# Generated by Django 5.1.15 on 2026-09-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_rawscrape_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='target',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='target',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('scraping', 'Scraping'), ('evaluating', 'Evaluating'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
