# Generated by Django 5.1.15 on 2026-09-20 02:29

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_question_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burneraccount',
            name='password',
            field=core.fields.EncryptedTextField(),
        ),
    ]
